trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'myapp'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'dockerRegistryServiceConnection'
    tags: |
      $(Build.BuildId)

- script: |
    docker stop myapp || true
    docker rm myapp || true
    docker run -d --name myapp -p 8080:80 myapp:$(Build.BuildId)
  displayName: 'Deploy Docker container'