trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'dockerRegistryServiceConnection'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'prete88/myportfolio'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'dockerRegistryServiceConnection'
    tags: |
      $(Build.BuildId)

- script: |
    kubectl apply -f deployment.yaml
  displayName: 'Deploy to Kubernetes'
