apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myportfolio
  template:
    metadata:
      labels:
        app: myportfolio
    spec:
      containers:
      - name: myportfolio
        image: prete88/myportfolio
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myportfolio-service
spec:
  type: NodePort
  selector:
    app: myportfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001